/**
 * WordPress Connection
 * 
 * Phase 13: WordPress REST API connector for publishing websites.
 */

import { createHash } from 'crypto';
import { PrismaClient } from '@prisma/client';

// ============================================================================
// Types
// ============================================================================

export interface WordPressConfig {
  siteUrl: string;
  username: string;
  appPassword: string;
}

export interface PageResult {
  success: boolean;
  pageId?: number;
  pageUrl?: string;
  error?: string;
}

export interface MediaUploadResult {
  success: boolean;
  mediaId?: number;
  url?: string;
  error?: string;
}

// ============================================================================
// WordPress REST API Client
// ============================================================================

export class WordPressClient {
  private baseUrl: string;
  private authHeader: string;

  constructor(config: WordPressConfig) {
    this.baseUrl = config.siteUrl.replace(/\/$/, '');
    const credentials = Buffer.from(`${config.username}:${config.appPassword}`).toString('base64');
    this.authHeader = `Basic ${credentials}`;
  }

  private async request<T>(endpoint: string, options: RequestInit = {}): Promise<T> {
    const url = `${this.baseUrl}/wp-json/wp/v2${endpoint}`;
    
    const response = await fetch(url, {
      ...options,
      headers: {
        'Authorization': this.authHeader,
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(`WordPress API error: ${response.status} - ${JSON.stringify(data)}`);
    }

    return data as T;
  }

  /**
   * Create a new page
   */
  async createPage(data: {
    title: string;
    content?: string;
    slug?: string;
    status?: 'draft' | 'publish' | 'pending';
    parent?: number;
  }): Promise<{ id: number; link: string }> {
    return this.request('/pages', {
      method: 'POST',
      body: JSON.stringify({
        title: data.title,
        content: data.content || '',
        slug: data.slug,
        status: data.status || 'draft',
        parent: data.parent,
      }),
    });
  }

  /**
   * Update a page
   */
  async updatePage(pageId: number, data: {
    title?: string;
    content?: string;
    status?: 'draft' | 'publish' | 'pending';
  }): Promise<{ id: number; link: string }> {
    return this.request(`/pages/${pageId}`, {
      method: 'POST',
      body: JSON.stringify(data),
    });
  }

  /**
   * Write Elementor data to page meta
   */
  async writeElementorData(pageId: number, elementorData: unknown[]): Promise<void> {
    const jsonString = JSON.stringify(elementorData);
    
    try {
      await this.request(`/pages/${pageId}/meta`, {
        method: 'POST',
        body: JSON.stringify({
          key: '_elementor_data',
          value: jsonString,
        }),
      });
    } catch (error) {
      console.warn('Meta endpoint failed:', error);
      throw new Error(
        'Direct meta writing failed. Ensure Elementor is installed and ' +
        'a compatible plugin exposes the meta endpoint.'
      );
    }
  }

  /**
   * Trigger Elementor CSS regeneration
   */
  async triggerCssRegeneration(pageId: number): Promise<void> {
    // Try Elementor REST API
    try {
      await fetch(`${this.baseUrl}/wp-json/elementor/v1/post/${pageId}`, {
        method: 'POST',
        headers: {
          'Authorization': this.authHeader,
        },
      });
      console.log('Elementor CSS regeneration triggered via REST API');
      return;
    } catch {
      // Continue to AJAX fallback
    }

    // Fallback: Use admin-ajax.php
    try {
      await fetch(`${this.baseUrl}/wp-admin/admin-ajax.php`, {
        method: 'POST',
        headers: {
          'Authorization': this.authHeader,
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: new URLSearchParams({
          action: 'elementor_update_css',
          post_id: String(pageId),
        }),
      });
      console.log('Elementor CSS regeneration triggered via AJAX');
    } catch (error) {
      console.warn('AJAX CSS regeneration failed:', error);
    }
  }

  /**
   * Publish a complete Elementor page
   */
  async publishElementorPage(
    title: string,
    elementorData: unknown[],
    options?: { slug?: string; status?: 'draft' | 'publish'; }
  ): Promise<PageResult> {
    try {
      const page = await this.createPage({
        title,
        slug: options?.slug,
        status: options?.status || 'draft',
        content: '<!-- Generated by SiteForge AI -->',
      });

      await this.writeElementorData(page.id, elementorData);
      await this.triggerCssRegeneration(page.id);

      if (options?.status === 'publish') {
        await this.updatePage(page.id, { status: 'publish' });
      }

      return {
        success: true,
        pageId: page.id,
        pageUrl: page.link,
      };
    } catch (error) {
      return { success: false, error: String(error) };
    }
  }

  /**
   * Upload media to WordPress
   */
  async uploadMedia(buffer: Buffer, filename: string, mimeType: string): Promise<MediaUploadResult> {
    try {
      const response = await fetch(`${this.baseUrl}/wp-json/wp/v2/media`, {
        method: 'POST',
        headers: {
          'Authorization': this.authHeader,
          'Content-Disposition': `attachment; filename="${filename}"`,
          'Content-Type': mimeType,
        },
        body: new Uint8Array(buffer),
      });

      if (!response.ok) {
        const error = await response.json();
        return { success: false, error: JSON.stringify(error) };
      }

      const data = await response.json();
      return {
        success: true,
        mediaId: data.id,
        url: data.source_url,
      };
    } catch (error) {
      return { success: false, error: String(error) };
    }
  }

  /**
   * Test connection to WordPress
   */
  async testConnection(): Promise<{ success: boolean; error?: string }> {
    try {
      await this.request('/users/me');
      return { success: true };
    } catch (error) {
      return { success: false, error: String(error) };
    }
  }
}

// ============================================================================
// Connection Management
// ============================================================================

const ENCRYPTION_KEY = process.env.ENCRYPTION_KEY || 'siteforge-default-key';

function encryptPassword(password: string): string {
  return Buffer.from(password).toString('base64');
}

function decryptPassword(encrypted: string): string {
  return Buffer.from(encrypted, 'base64').toString('utf8');
}

/**
 * Save WordPress connection for a user
 */
export async function saveWordPressConnection(
  userId: string,
  siteUrl: string,
  username: string,
  appPassword: string
): Promise<void> {
  const prisma = new PrismaClient();
  
  await prisma.wordPressConnection.upsert({
    where: { userId },
    create: {
      userId,
      siteUrl,
      username,
      appPassword: encryptPassword(appPassword),
    },
    update: {
      siteUrl,
      username,
      appPassword: encryptPassword(appPassword),
    },
  });
}

/**
 * Get WordPress connection for a user
 */
export async function getWordPressConnection(userId: string): Promise<WordPressConfig | null> {
  const prisma = new PrismaClient();
  
  const connection = await prisma.wordPressConnection.findUnique({
    where: { userId },
  });
  
  if (!connection) return null;
  
  return {
    siteUrl: connection.siteUrl,
    username: connection.username,
    appPassword: decryptPassword(connection.appPassword),
  };
}

/**
 * Remove WordPress connection
 */
export async function removeWordPressConnection(userId: string): Promise<void> {
  const prisma = new PrismaClient();
  
  await prisma.wordPressConnection.delete({
    where: { userId },
  });
}

/**
 * Publish website to WordPress
 */
export async function publishToWordPress(
  userId: string,
  projectId: string,
  pages: Array<{
    title: string;
    slug: string;
    elementorData: unknown[];
    status?: 'draft' | 'publish';
  }>
): Promise<{
  success: boolean;
  publishedPages?: Array<{ title: string; url: string }>;
  errors?: string[];
}> {
  const connection = await getWordPressConnection(userId);
  
  if (!connection) {
    return { success: false, errors: ['WordPress connection not configured'] };
  }
  
  const client = new WordPressClient(connection);
  const publishedPages: Array<{ title: string; url: string }> = [];
  const errors: string[] = [];
  
  for (const page of pages) {
    const result = await client.publishElementorPage(page.title, page.elementorData, {
      slug: page.slug,
      status: page.status,
    });
    
    if (result.success && result.pageUrl) {
      publishedPages.push({ title: page.title, url: result.pageUrl });
      
      const prisma = new PrismaClient();
      await prisma.deployment.create({
        data: {
          projectId,
          wordpressUrl: result.pageUrl,
          pageId: String(result.pageId),
          status: 'COMPLETE',
        },
      });
    } else {
      errors.push(`${page.title}: ${result.error}`);
    }
  }
  
  return {
    success: errors.length === 0,
    publishedPages,
    errors: errors.length > 0 ? errors : undefined,
  };
}
